[package]
name        = "template-rs"
version     = "0.1.0"
description = "<crate description>"
authors     = ["RJ Rybarczyk <rj@rybar.tech>"]
license     = "CC0-1.0"
homepage    = "https://github.com/rrybarczyk/template-rs"
readme      = "README.md"
edition     = "2018"

[dependencies]
